name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. show file list
      run: ls -al
    - name: check pip list
      run: pip list
    - name: pip upgrade
      run: python -m pip install --upgrade pip
    - name: set envirment
      run: pip install -r requirements.txt
    - name: run scripts
      run: python test.py
